
from .models import Review
from django import forms
from django.utils.safestring import mark_safe


class FormReview(forms.ModelForm):
    # Credit for adapted choices on TypedChoiceField
    # See README.md for more details
    rating = forms.TypedChoiceField(
        choices=(
            (1, mark_safe('<p class="highlight text-center altFont"> Rubbish!')),
            (2, mark_safe('<p class="highlight text-center altFont"> Ok I guess</p>')),
            (3, mark_safe('<p class="highlight text-center altFont"> Averagely average')),
            (4, mark_safe('<p class="highlight text-center altFont"> Pleasantly impressed')),
            (5, mark_safe('<p class="highlight text-center altFont"> Outstanding'))
            ),
        widget=forms.RadioSelect,
    )

    class Meta:
        model = Review
        fields = ['review', 'rating']
        exclude = ['added_by']
        widgets = {
            'review': forms.Textarea(attrs={'placeholder': 'Tell us what you think...', 'class':'altFont'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove labels auto generated by form
        self.fields['review'].label = False
        self.fields['rating'].label = False
