# Imports
from .models import Review
from django import forms
from django.utils.safestring import mark_safe


# Review form
class FormReview(forms.ModelForm):
    # Credit for adapted choices on TypedChoiceField
    # See README.md for more details
    rating = forms.TypedChoiceField(
        choices=(
            (1, mark_safe('<p><i class="fa fa-star highlight"></i>\
                <i class="fa fa-star"></i><i class="fa fa-star"></i>\
                <i class="fa fa-star"></i><i class="fa fa-star"></i> \
                <span class="text-center altFont">Extremely Unsatisfied\
                </span></p>')),
            (2, mark_safe('<p><i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i><i class="fa fa-star">\
                </i><i class="fa fa-star"></i><i class="fa fa-star"></i> \
                <span class="text-center altFont"> Unsatisfied\
                </span></p>')),
            (3, mark_safe('<p><i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i><i class="fa fa-star">\
                </i><i class="fa fa-star"></i> \
                <span class="text-center altFont"> Neutral</span></p>')),
            (4, mark_safe('<p><i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i><i class="fa fa-star">\
                </i> <span class="text-center altFont"> Satisfied\
                </span></p>')),
            (5, mark_safe('<p><i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i>\
                <i class="fa fa-star highlight"></i> \
                <span class="text-center altFont"> Extremely satisfied!\
                </span></p>'))
            ),
        widget=forms.RadioSelect,
    )

    class Meta:
        model = Review
        fields = ['review', 'rating']
        exclude = ['added_by']
        widgets = {
            'review': forms.Textarea(attrs={'\
            placeholder': 'Tell us what you think...', 'class': 'altFont'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Remove labels auto generated by form
        self.fields['review'].label = False
        self.fields['rating'].label = False
