# Generated by Django 3.2.5 on 2021-08-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
