# Generated by Django 3.2.5 on 2021-08-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crate', '0002_coupon_coupon_id'),
        ('checkout', '0006_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crate.coupon'),
        ),
    ]
