# Generated by Django 3.2.5 on 2021-08-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crate', '0003_remove_coupon_coupon_id'),
        ('checkout', '0007_order_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_id',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crate.coupon'),
        ),
    ]
