# Generated by Django 3.2.5 on 2021-07-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'Supplies'},
        ),
    ]
