# Generated by Django 3.2.5 on 2021-08-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crate', '0002_coupon_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_id',
        ),
    ]
